# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('users', '0006_auto_20161110_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADGroupMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_group_name', models.CharField(max_length=32, verbose_name='AD group name')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ad_group_mapping', to='auth.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name_plural': 'AD group mappings',
                'verbose_name': 'AD group mapping',
            },
        ),
    ]
