# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-30 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0050_add_reservation_host_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'permissions': (('can_make_reservation', 'Can make reservation'),), 'verbose_name': 'resource', 'verbose_name_plural': 'resources'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',), 'permissions': (('can_approve_reservation', 'Can approve reservation'), ('can_view_reservation_access_code', 'Can view reservation access code')), 'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
    ]
