# Generated by Django 2.1.9 on 2019-07-17 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0081_add_more_reservation_extra_fields'),
        ('resources', '0079_reservation_extra_questions'),
    ]

    operations = [
    ]
